spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    database-platform: com.example.jpa_postgresql.config.CustomDialectConfig
    open-in-view: false